import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { buildPlan } from '../../src/decision-matrix.js'
import { runCdsAddFrontend } from '../../src/steps/03-cds-add-frontend.js'
import { patchMta } from '../../src/steps/05-patch-mta.js'

const directories = []

async function project() {
  const directory = await mkdtemp(join(tmpdir(), 'capx-phase5-'))
  directories.push(directory)
  return directory
}

afterEach(async () => {
  await Promise.all(
    directories
      .splice(0)
      .map((directory) =>
        import('node:fs/promises').then(({ rm }) =>
          rm(directory, { recursive: true, force: true }),
        ),
      ),
  )
})

describe('Phase 5 frontend orchestration', () => {
  it('defers html5-repo until after the frontend facet when an approuter is selected', async () => {
    const plan = buildPlan({
      name: 'bookshop',
      lang: 'js',
      devDb: 'sqlite',
      prodDb: 'hana',
      auth: 'xsuaa',
      frontend: 'vue',
    })
    const exec = vi.fn().mockResolvedValue({})

    expect(plan.facets).toContain('approuter')
    expect(plan.facets).toContain('destination')
    expect(plan.facets).not.toContain('html5-repo')
    expect(plan.postInitFacets).toEqual(['vue', 'html5-repo'])

    await runCdsAddFrontend('/tmp/bookshop', plan, { exec })

    expect(exec.mock.calls).toEqual([
      ['cds', ['add', 'vue', '--into', 'frontend'], { cwd: '/tmp/bookshop', stdio: 'inherit' }],
      ['cds', ['add', 'html5-repo'], { cwd: '/tmp/bookshop', stdio: 'inherit' }],
    ])
  })

  it('adds a standalone frontend without html5-repo when no approuter is selected', async () => {
    const plan = buildPlan({
      name: 'bookshop',
      lang: 'js',
      devDb: 'sqlite',
      prodDb: 'hana',
      auth: 'none',
      frontend: 'react',
      approuter: false,
    })
    const exec = vi.fn().mockResolvedValue({})

    expect(plan.postInitFacets).toEqual(['react'])
    await runCdsAddFrontend('/tmp/bookshop', plan, { exec })

    expect(exec.mock.calls).toEqual([
      ['cds', ['add', 'react', '--into', 'frontend'], { cwd: '/tmp/bookshop', stdio: 'inherit' }],
    ])
  })
})

describe('patchMta', () => {
  it('renames generated modules and references while retaining comments and the database deployer', async () => {
    const directory = await project()
    await writeFile(
      join(directory, 'mta.yaml'),
      `# Generated by CDS\n_schema-version: '3.3'\nID: old-bookshop\nmodules:\n  # service comment\n  - name: generated-srv\n    type: nodejs\n    path: gen/srv\n    requires:\n      - name: generated-db\n  - name: generated-db-deployer\n    type: hdb\n    path: gen/db\n    requires:\n      - name: generated-db\n  - name: generated-frontend\n    type: html5\n    path: app/frontend\n    build-parameters:\n      builder: custom\n      commands:\n        - npm ci\n        - npm run build\n  - name: generated-router\n    type: approuter.nodejs\n    path: app/router\n    requires:\n      - name: generated-srv\n      - name: generated-html5-runtime\n  - name: generated-app-deployer\n    type: com.sap.application.content\n    build-parameters:\n      requires:\n        - name: generated-frontend\n          artifacts:\n            - frontend.zip\nresources:\n  - name: generated-db\n    type: com.sap.xs.hdi-container\n  - name: generated-html5-runtime\n    type: org.cloudfoundry.managed-service\n    parameters:\n      service: html5-apps-repo\n      service-plan: app-runtime\n`,
    )

    await patchMta(directory, { name: 'bookshop', frontend: 'vue', approuter: true })

    const mta = await readFile(join(directory, 'mta.yaml'), 'utf8')
    expect(mta).toContain('# Generated by CDS')
    expect(mta).toContain('# service comment')
    expect(mta).toContain('name: bookshop-srv')
    expect(mta).toContain('name: bookshop-db-deployer')
    expect(mta).toContain('name: bookshop-frontend')
    expect(mta).toContain('name: bookshop-approuter')
    expect(mta).toContain('name: bookshop-db')
    expect(mta).toContain('- name: bookshop-srv')
    expect(mta).toContain('- name: bookshop-db')
    expect(mta).toContain('- name: bookshop-frontend\n          artifacts:')
    expect(mta).toContain('service-plan: app-runtime')
    expect(mta).toContain('commands:\n        - npm ci\n        - npm run build')
  })

  it('patches generated router routes without discarding other fields or routes', async () => {
    const directory = await project()
    await writeFile(join(directory, 'mta.yaml'), 'modules: []\nresources: []\n')
    await mkdir(join(directory, 'app', 'router'), { recursive: true })
    await writeFile(
      join(directory, 'app', 'router', 'xs-app.json'),
      JSON.stringify({
        welcomeFile: '/existing.html',
        authenticationMethod: 'route',
        custom: true,
        routes: [
          { source: '^/existing/(.*)$', destination: 'existing-api' },
          { source: '^/(.*)$', localDir: 'resources' },
        ],
      }),
    )

    await patchMta(directory, { name: 'bookshop', frontend: 'react', approuter: true })

    const router = JSON.parse(
      await readFile(join(directory, 'app', 'router', 'xs-app.json'), 'utf8'),
    )
    expect(router).toMatchObject({
      welcomeFile: '/existing.html',
      authenticationMethod: 'route',
      custom: true,
    })
    expect(router.routes).toContainEqual({
      source: '^/existing/(.*)$',
      destination: 'existing-api',
    })
    expect(router.routes).toContainEqual({
      source: '^/odata/(.*)$',
      target: '/odata/$1',
      destination: 'srv-api',
      csrfProtection: false,
    })
    expect(router.routes).toContainEqual({
      source: '^(.*)$',
      target: '$1',
      service: 'html5-apps-repo-rt',
    })
    expect(router.routes).not.toContainEqual({ source: '^/(.*)$', localDir: 'resources' })
  })
})
